### ISSUE TITLE
Deploying to BTP Trial Account

### ISSUE THREAD

**Issue by bigsmity** [gregorwolf/pg-beershop#323]
Hi Gregor,

I was wondering if you could help me out with an error please?

I am attempting to deploy this example to a btp trial account to gain some experience while upgrading one of our existing applications. Strangely I have come across the same error in our environment with my application as the trial environment with your example source code.

I created a brand new trial account to test and setup the service instance of "PostgreSQL, hyperscaler option" as "postgresql-db" with the service-plan "trial"

As per "Run on SAP Business Technology Platform - Cloud Foundry Environment with Hyperscaler Option" running:

- npm run build:cf
- npm run deploy:cf

The error in the terminal is:

_Service operation failed: Controller operation failed: 502 Updating service "pg-beershop-database" failed: Bad Gateway: Error creating service "pg-beershop-database" from offering "postgresql-db" and plan "trial": CF-ServiceBrokerRequestRejected(10001): Service broker error: Service broker backing-services-broker-postgresql-db-cf-us10-001 failed with: You do not have sufficient entitlements for trial_

*on the free tier environment the service-plan 'free' is referenced in the same error.

cf dmol contains:

_#2.0#2022 09 30 01:17:15.853#Z#ERROR#com.sap.cloud.lm.sl.xs2.9633d9d9-405d-11ed-96bc-eeee0a821b93.OPERATION.CreateServiceTask#
######org.cloudfoundry.multiapps.controller.persistence.services.ProcessLogger########flowable-async-job-executor-thread-3569###
Exception caught#

org.cloudfoundry.multiapps.common.SLException: Service operation failed: Controller operation failed: 502 Updating service "pg-beershop-database" failed: Bad Gateway: Error creating service "pg-beershop-database" from offering "postgresql-db" and plan "trial": CF-ServiceBrokerRequestRejected(10001): Service broker error: Service broker backing-services-broker-postgresql-db-cf-us10-001 failed with: You do not have sufficient entitlements for trial 
	at org.cloudfoundry.multiapps.controller.process.steps.SyncFlowableStep.processException(SyncFlowableStep.java:131) ~[multiapps-controller-process-1.141.1.jar:?]
	at org.cloudfoundry.multiapps.controller.process.steps.SyncFlowableStep.onStepError(SyncFlowableStep.java:126) ~[multiapps-controller-process-1.141.1.jar:?]
	at org.cloudfoundry.multiapps.controller.process.steps.SyncFlowableStep.handleException(SyncFlowableStep.java:102) ~[multiapps-controller-process-1.141.1.jar:?]
	at org.cloudfoundry.multiapps.controller.process.steps.SyncFlowableStep.executeInternal(SyncFlowableStep.java:81) ~[multiapps-controller-process-1.141.1.jar:?]
	at org.cloudfoundry.multiapps.controller.process.steps.SyncFlowableStep.lambda$execute$0(SyncFlowableStep.java:65) ~[multiapps-controller-process-1.141.1.jar:?]
	at org.cloudfoundry.multiapps.controller.core.util.LoggingUtil.logWithCorrelationId(LoggingUtil.java:14) ~[multiapps-controller-core-1.141.1.jar:?]
	at org.cloudfoundry.multiapps.controller.process.steps.SyncFlowableStep.execute(SyncFlowableStep.java:65) ~[multiapps-controller-process-1.141.1.jar:?]
	at org.flowable.engine.impl.delegate.invocation.JavaDelegateInvocation.invoke(JavaDelegateInvocation.java:35) ~[flowable-engine-6.6.0.jar:6.6.0]
	at org.flowable.engine.impl.delegate.invocation.DelegateInvocation.proceed(DelegateInvocation.java:32) ~[flowable-engine-6.6.0.jar:6.6.0]
	at org.flowable.engine.impl.delegate.invocation.DefaultDelegateInterceptor.handleInvocation(DefaultDelegateInterceptor.java:26) ~[flowable-engine-6.6.0.jar:6.6.0]
	at org.flowable.engine.impl.bpmn.behavior.ServiceTaskDelegateExpressionActivityBehavior.execute(ServiceTaskDelegateExpressionActivityBehavior.java:157) ~[flowable-engine-6.6.0.jar:6.6.0]
	at org.flowable.engine.impl.agenda.ContinueProcessOperation.executeActivityBehavior(ContinueProcessOperation.java:313) ~[flowable-engine-6.6.0.jar:6.6.0]
	at org.flowable.engine.impl.agenda.ContinueProcessOperation.executeSynchronous(ContinueProcessOperation.java:170) ~[flowable-engine-6.6.0.jar:6.6.0]
	at org.flowable.engine.impl.agenda.ContinueProcessOperation.continueThroughFlowNode(ContinueProcessOperation.java:125) ~[flowable-engine-6.6.0.jar:6.6.0]
	at org.flowable.engine.impl.agenda.ContinueProcessOperation.run(ContinueProcessOperation.java:88) ~[flowable-engine-6.6.0.jar:6.6.0]
	at org.flowable.common.engine.impl.AbstractEngineConfiguration.lambda$new$0(AbstractEngineConfiguration.java:173) ~[flowable-engine-common-6.6.0.jar:6.6.0]
	at org.flowable.engine.impl.interceptor.CommandInvoker.executeOperation(CommandInvoker.java:97) ~[flowable-engine-6.6.0.jar:6.6.0]
	at org.flowable.engine.impl.interceptor.CommandInvoker.executeOperations(CommandInvoker.java:81) ~[flowable-engine-6.6.0.jar:6.6.0]
	at org.flowable.engine.impl.interceptor.CommandInvoker.execute(CommandInvoker.java:64) ~[flowable-engine-6.6.0.jar:6.6.0]
	at org.flowable.engine.impl.interceptor.BpmnOverrideContextInterceptor.execute(BpmnOverrideContextInterceptor.java:26) ~[flowable-engine-6.6.0.jar:6.6.0]
	at org.flowable.common.engine.impl.interceptor.TransactionContextInterceptor.execute(TransactionContextInterceptor.java:53) ~[flowable-engine-common-6.6.0.jar:6.6.0]
	at org.flowable.common.engine.impl.interceptor.CommandContextInterceptor.execute(CommandContextInterceptor.java:83) ~[flowable-engine-common-6.6.0.jar:6.6.0]
	at org.flowable.common.spring.SpringTransactionInterceptor.lambda$execute$0(SpringTransactionInterceptor.java:57) ~[flowable-spring-common-6.6.0.jar:6.6.0]
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140) [spring-tx-5.3.20.jar:5.3.20]
	at org.flowable.common.spring.SpringTransactionInterceptor.execute(SpringTransactionInterceptor.java:57) [flowable-spring-common-6.6.0.jar:6.6.0]
	at org.flowable.common.engine.impl.interceptor.LogInterceptor.execute(LogInterceptor.java:30) [flowable-engine-common-6.6.0.jar:6.6.0]
	at org.flowable.common.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:56) [flowable-engine-common-6.6.0.jar:6.6.0]
	at org.flowable.common.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:51) [flowable-engine-common-6.6.0.jar:6.6.0]
	at org.flowable.job.service.impl.asyncexecutor.ExecuteAsyncRunnable.executeJob(ExecuteAsyncRunnable.java:127) [flowable-job-service-6.6.0.jar:6.6.0]
	at org.flowable.job.service.impl.asyncexecutor.ExecuteAsyncRunnable.run(ExecuteAsyncRunnable.java:115) [flowable-job-service-6.6.0.jar:6.6.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: com.sap.cloudfoundry.client.facade.CloudControllerException: Controller operation failed: 502 Updating service "pg-beershop-database" failed: Bad Gateway: Error creating service "pg-beershop-database" from offering "postgresql-db" and plan "trial": CF-ServiceBrokerRequestRejected(10001): Service broker error: Service broker backing-services-broker-postgresql-db-cf-us10-001 failed with: You do not have sufficient entitlements for trial
	at org.cloudfoundry.multiapps.controller.process.steps.SyncFlowableStep.handleControllerException(SyncFlowableStep.java:136) ~[multiapps-controller-process-1.141.1.jar:?]
	at org.cloudfoundry.multiapps.controller.process.steps.SyncFlowableStep.processException(SyncFlowableStep.java:130) ~[multiapps-controller-process-1.141.1.jar:?]
	... 32 more
Caused by: com.sap.cloudfoundry.client.facade.CloudOperationException: 502 Updating service "pg-beershop-database" failed: Bad Gateway: Error creating service "pg-beershop-database" from offering "postgresql-db" and plan "trial": CF-ServiceBrokerRequestRejected(10001): Service broker error: Service broker backing-services-broker-postgresql-db-cf-us10-001 failed with: You do not have sufficient entitlements for trial
	at org.cloudfoundry.multiapps.controller.process.steps.ServiceStep.executeOperationAndHandleExceptions(ServiceStep.java:57) ~[multiapps-controller-process-1.141.1.jar:?]
	at org.cloudfoundry.multiapps.controller.process.steps.ServiceStep.executeAsyncStep(ServiceStep.java:31) ~[multiapps-controller-process-1.141.1.jar:?]
	at org.cloudfoundry.multiapps.controller.process.steps.AsyncFlowableStep.executeStep(AsyncFlowableStep.java:18) ~[multiapps-controller-process-1.141.1.jar:?]
	at org.cloudfoundry.multiapps.controller.process.steps.SyncFlowableStep.executeInternal(SyncFlowableStep.java:75) ~[multiapps-controller-process-1.141.1.jar:?]
	... 29 more
Caused by: com.sap.cloudfoundry.client.facade.CloudServiceBrokerException: Service broker operation failed: 502 Bad Gateway: Error creating service "pg-beershop-database" from offering "postgresql-db" and plan "trial": CF-ServiceBrokerRequestRejected(10001): Service broker error: Service broker backing-services-broker-postgresql-db-cf-us10-001 failed with: You do not have sufficient entitlements for trial
	at org.cloudfoundry.multiapps.controller.process.steps.CreateServiceStep.processServiceCreationFailure(CreateServiceStep.java:87) ~[multiapps-controller-process-1.141.1.jar:?]
	at org.cloudfoundry.multiapps.controller.process.steps.CreateServiceStep.executeOperation(CreateServiceStep.java:41) ~[multiapps-controller-process-1.141.1.jar:?]
	at org.cloudfoundry.multiapps.controller.process.steps.ServiceStep.executeOperationAndHandleExceptions(ServiceStep.java:54) ~[multiapps-controller-process-1.141.1.jar:?]
	at org.cloudfoundry.multiapps.controller.process.steps.ServiceStep.executeAsyncStep(ServiceStep.java:31) ~[multiapps-controller-process-1.141.1.jar:?]
	at org.cloudfoundry.multiapps.controller.process.steps.AsyncFlowableStep.executeStep(AsyncFlowableStep.java:18) ~[multiapps-controller-process-1.141.1.jar:?]
	at org.cloudfoundry.multiapps.controller.process.steps.SyncFlowableStep.executeInternal(SyncFlowableStep.java:75) ~[multiapps-controller-process-1.141.1.jar:?]
	... 29 more_

Would you have any information if anything has changed with the required configuration? I am quite stuck on this one, any information or assistance is most appreciated.

Thanks,
Brad Smith.

**Comment by gregorwolf** [comment]
Have you tried deploying my sample app https://github.com/gregorwolf/pg-beershop? Before you do so create the existing PostgreSQL instance and deploy the MTAR.

**Comment by bigsmity** [comment]
> Have you tried deploying my sample app https://github.com/gregorwolf/pg-beershop? Before you do so create the existing PostgreSQL instance and deploy the MTAR.

Yes, this is exactly what I have attempted resulting in the error above.

**Comment by gregorwolf** [comment]
@bigsmity sorry, didn't noticed that this issue was created in the pg-beershop project ;-). I've just tried a deployment in a trial account that was created in January 2022. It worked without issues there. Also I've tried in a subaccount created in April 2022. Also no issues there. Now I give it another try in a freshly creted subaccount. I already see that the CF API Endpoint for the old accounts is:

https://api.cf.us10.hana.ondemand.com/

for the new one it's:

https://api.cf.us10-001.hana.ondemand.com/

**Comment by gregorwolf** [comment]
Hi @bigsmity,

in my freshly created trial account the same issue occurs:

```
[cds-dbm] - starting delta database deployment of service db
cds-dbm deploy [services]
Dynamically identifies changes in your cds data model and deploys them to the
database
Options:
--help           Show help                                       [boolean]
--version        Show version number                             [boolean]
-s, --service                                                [default: ["db"]]
-a, --auto-undeploy
-d, --dry
-l, --load-via
-c, --create-db
Error: connect ETIMEDOUT 10.16.50.120:4402
at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1237:16) {
errno: -110,
code: 'ETIMEDOUT',
syscall: 'connect',
address: '10.16.50.120',
port: 4402
}
npm notice
npm notice New minor version of npm available! 8.12.1 -> 8.19.2
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v8.19.2>
npm notice Run `npm install -g npm@8.19.2` to update!
npm notice
Exit status 1
```

Please follow the SAP Community Question: [SAP BTP PostgreSQL instance not reachable](https://answers.sap.com/questions/13731374/sap-btp-postgresql-instance-not-reachable.html) to hopefully get some feedback from SAP.

Best Regards
Gregor

**Comment by bigsmity** [comment]
> Hi @bigsmity,
> 
> in my freshly created trial account the same issue occurs:
> 
> ```
> [cds-dbm] - starting delta database deployment of service db
> cds-dbm deploy [services]
> Dynamically identifies changes in your cds data model and deploys them to the
> database
> Options:
> --help           Show help                                       [boolean]
> --version        Show version number                             [boolean]
> -s, --service                                                [default: ["db"]]
> -a, --auto-undeploy
> -d, --dry
> -l, --load-via
> -c, --create-db
> Error: connect ETIMEDOUT 10.16.50.120:4402
> at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1237:16) {
> errno: -110,
> code: 'ETIMEDOUT',
> syscall: 'connect',
> address: '10.16.50.120',
> port: 4402
> }
> npm notice
> npm notice New minor version of npm available! 8.12.1 -> 8.19.2
> npm notice Changelog: <https://github.com/npm/cli/releases/tag/v8.19.2>
> npm notice Run `npm install -g npm@8.19.2` to update!
> npm notice
> Exit status 1
> ```
> 
> Please follow the SAP Community Question: [SAP BTP PostgreSQL instance not reachable](https://answers.sap.com/questions/13731374/sap-btp-postgresql-instance-not-reachable.html) to hopefully get some feedback from SAP.
> 
> Best Regards Gregor

Hi Gregor,

Thank you for getting back to me. 

Do you think this is the underlying cause? I am not seeing a timeout error in my logs, the only error is:

Service operation failed: Controller operation failed: 502 Updating service "pg-beershop-database" failed: Bad Gateway: Error creating service "pg-beershop-database" from offering "postgresql-db" and plan "trial": CF-ServiceBrokerRequestRejected(10001): Service broker error: Service broker backing-services-broker-postgresql-db-cf-us10-001 failed with: You do not have sufficient entitlements for trial

The service has been setup as per the attachemnt but I feel like I am missing a step?

Thanks,
Brad.


![postgresql_btp_1](https://user-images.githubusercontent.com/914277/193709608-9bd9c19c-24c6-4087-ac00-f8795f29133c.PNG)

**Comment by bigsmity** [comment]
@gregorwolf I have found the issue with the deployment, I have configured the service instance name wrong. It is quite obvious to me now. 

I am now seeing the timeout mentioned above when running the app.

Thank you for your time and help,
Brad.

**Comment by gregorwolf** [comment]
Hi @bigsmity,

Please follow the SAP Community Question: [SAP BTP PostgreSQL instance not reachable](https://answers.sap.com/questions/13731374/sap-btp-postgresql-instance-not-reachable.html). I think it's an issue with the firewall settings of the new trial region that SAP setup. Someone from SAP already replied in the tread.

Best Regards
Gregor

**Comment by bigsmity** [comment]
@gregorwolf Thank you, I will follow there.
