### ISSUE TITLE
cannot deploy to Cloud foundary

### ISSUE THREAD

**Issue by fedorsh1984** [gregorwolf/pg-beershop#74]
Hi. Trying to deploy the project and get the error 
Execution of task "deploy-to-postgresql" on application "pg-beershop-db-deployer-apt" failed.
Download the application logs via the dmol command and check them for more information.
A step of the process has failed. Retrying it may solve the issue.
Proceeding with automatic retry... (1 of 3 attempts left)
Executing task "deploy-to-postgresql" on application "pg-beershop-db-deployer-apt"...
Error starting application "pg-beershop-srv": Some instances have crashed. Check the logs of your application for more information.
Download the application logs via the dmol command and check them for more information.
A step of the process has failed. Retrying it may solve the issue.
Process failed.
Use "cf deploy -i 059f0d53-bffe-11eb-b3e3-eeee0a9c1a77 -a abort" to abort the process.
Use "cf deploy -i 059f0d53-bffe-11eb-b3e3-eeee0a9c1a77 -a retry" to retry the process.
Use "cf dmol -i 059f0d53-bffe-11eb-b3e3-eeee0a9c1a77" to download the logs of the process.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pg-beershop@1.0.0 deploy:cf: `cf deploy mta_archives/pg-beershop_1.0.0.mtar`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pg-beershop@1.0.0 deploy:cf script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

log
   2021-05-28T21:48:05.48+0000 [APP/TASK/deploy-to-postgresql/0] ERR cds-dbm deploy [services]
   2021-05-28T21:48:05.48+0000 [APP/TASK/deploy-to-postgresql/0] ERR Dynamically identifies changes in your cds data model and deploys them to the
   2021-05-28T21:48:05.48+0000 [APP/TASK/deploy-to-postgresql/0] ERR database
   2021-05-28T21:48:05.48+0000 [APP/TASK/deploy-to-postgresql/0] ERR Options:
   2021-05-28T21:48:05.48+0000 [APP/TASK/deploy-to-postgresql/0] ERR       --help           Show help                                       [boolean]
   2021-05-28T21:48:05.48+0000 [APP/TASK/deploy-to-postgresql/0] ERR       --version        Show version number                             [boolean]
   2021-05-28T21:48:05.48+0000 [APP/TASK/deploy-to-postgresql/0] ERR   -s, --service                                                [default: ["db"]]
   2021-05-28T21:48:05.48+0000 [APP/TASK/deploy-to-postgresql/0] ERR   -a, --auto-undeploy
   2021-05-28T21:48:05.48+0000 [APP/TASK/deploy-to-postgresql/0] ERR   -d, --dry
   2021-05-28T21:48:05.48+0000 [APP/TASK/deploy-to-postgresql/0] ERR   -l, --load-via
   2021-05-28T21:48:05.48+0000 [APP/TASK/deploy-to-postgresql/0] ERR   -c, --create-db
   2021-05-28T21:48:05.48+0000 [APP/TASK/deploy-to-postgresql/0] ERR error: relation "csw_breweryanalytics" does not exist
   2021-05-28T21:48:05.48+0000 [APP/TASK/deploy-to-postgresql/0] ERR     at Parser.parseErrorMessage (/home/vcap/deps/2/node_modules/pg-protocol/dist/parser.js:287:98)
   2021-05-28T21:48:05.48+0000 [APP/TASK/deploy-to-postgresql/0] ERR     at Parser.handlePacket (/home/vcap/deps/2/node_modules/pg-protocol/dist/parser.js:126:29)
   2021-05-28T21:48:05.48+0000 [APP/TASK/deploy-to-postgresql/0] ERR     at Parser.parse (/home/vcap/deps/2/node_modules/pg-protocol/dist/parser.js:39:38)
   2021-05-28T21:48:05.48+0000 [APP/TASK/deploy-to-postgresql/0] ERR     at TLSSocket.<anonymous> (/home/vcap/deps/2/node_modules/pg-protocol/dist/index.js:11:42)
   2021-05-28T21:48:05.48+0000 [APP/TASK/deploy-to-postgresql/0] ERR     at TLSSocket.emit (events.js:315:20)
   2021-05-28T21:48:05.48+0000 [APP/TASK/deploy-to-postgresql/0] ERR     at addChunk (internal/streams/readable.js:309:12)
   2021-05-28T21:48:05.48+0000 [APP/TASK/deploy-to-postgresql/0] ERR     at readableAddChunk (internal/streams/readable.js:284:9)
   2021-05-28T21:48:05.48+0000 [APP/TASK/deploy-to-postgresql/0] ERR     at TLSSocket.Readable.push (internal/streams/readable.js:223:10)
   2021-05-28T21:48:05.48+0000 [APP/TASK/deploy-to-postgresql/0] ERR     at TLSWrap.onStreamRead (internal/stream_base_commons.js:188:23) {
   2021-05-28T21:48:05.48+0000 [APP/TASK/deploy-to-postgresql/0] ERR   length: 120,
   2021-05-28T21:48:05.48+0000 [APP/TASK/deploy-to-postgresql/0] ERR   severity: 'ERROR',
   2021-05-28T21:48:05.48+0000 [APP/TASK/deploy-to-postgresql/0] ERR   code: '42P01',
   2021-05-28T21:48:05.48+0000 [APP/TASK/deploy-to-postgresql/0] ERR   detail: undefined,
   2021-05-28T21:48:05.48+0000 [APP/TASK/deploy-to-postgresql/0] ERR   hint: undefined,
   2021-05-28T21:48:05.48+0000 [APP/TASK/deploy-to-postgresql/0] ERR   position: '178',
   2021-05-28T21:48:05.48+0000 [APP/TASK/deploy-to-postgresql/0] ERR   internalPosition: undefined,
   2021-05-28T21:48:05.48+0000 [APP/TASK/deploy-to-postgresql/0] ERR   internalQuery: undefined,
   2021-05-28T21:48:05.48+0000 [APP/TASK/deploy-to-postgresql/0] ERR   where: undefined,
   2021-05-28T21:48:05.48+0000 [APP/TASK/deploy-to-postgresql/0] ERR   schema: undefined,
   2021-05-28T21:48:05.48+0000 [APP/TASK/deploy-to-postgresql/0] ERR   table: undefined,
   2021-05-28T21:48:05.48+0000 [APP/TASK/deploy-to-postgresql/0] ERR   column: undefined,
   2021-05-28T21:48:05.48+0000 [APP/TASK/deploy-to-postgresql/0] ERR   dataType: undefined,
   2021-05-28T21:48:05.48+0000 [APP/TASK/deploy-to-postgresql/0] ERR   constraint: undefined,
   2021-05-28T21:48:05.48+0000 [APP/TASK/deploy-to-postgresql/0] ERR   file: 'parse_relation.c',
   2021-05-28T21:48:05.48+0000 [APP/TASK/deploy-to-postgresql/0] ERR   line: '1180',
   2021-05-28T21:48:05.48+0000 [APP/TASK/deploy-to-postgresql/0] ERR   routine: 'parserOpenTable'
   2021-05-28T21:48:05.48+0000 [APP/TASK/deploy-to-postgresql/0] ERR }
   2021-05-28T21:48:05.50+0000 [APP/TASK/deploy-to-postgresql/0] OUT Exit status 1
   2021-05-28T21:48:05.92+0000 [CELL/0] OUT Cell e79e173c-0a75-4097-9d10-38f3447450db stopping instance 2873f113-dbdb-4d5e-a5d9-a22d8bad643c
   2021-05-28T21:48:05.92+0000 [CELL/0] OUT Cell e79e173c-0a75-4097-9d10-38f3447450db destroying container for instance 2873f113-dbdb-4d5e-a5d9-a22d8bad643c
   2021-05-28T21:48:09.28+0000 [CELL/0] OUT Cell e79e173c-0a75-4097-9d10-38f3447450db successfully destroyed container for instance 2873f113-dbdb-4d5e-a5d9-a22d8bad643c
   
   
[2021-05-28T21_48_02_859Z-debug (1).log](https://github.com/gregorwolf/pg-beershop/files/6563485/2021-05-28T21_48_02_859Z-debug.1.log)

**Comment by gregorwolf** [comment]
I had to fix an issue with the start of the srv module. Please check the latest commits.

**Comment by fedorsh1984** [comment]
Hi, Thanks it works. Why do you need pg-beershop-db-deployer-apt?

**Comment by gregorwolf** [comment]
The cds-dbm module needs a Java environment to run the provisioning of the database schema.

**Comment by fedorsh1984** [comment]
Thanks
